### PR TITLE
FJS-1044: 'OnBlur' Valdation is not working for email and phone number inputs

### PR DESCRIPTION
**Pull request by AlehKatsiubaFormIO**

### CODE REVIEW

**Comment by travist** [comment]
Tests are failing on this one.

**Comment by travist** [comment]
This will have other undesired consequences. ```checkData``` also performs calculations on change as well as performs conditional logic. This will basically make it so that if a component has "onBlur" validation, it's calculations and conditionals will fail to evaluate.  This needs more work.

**Comment by AlehKatsiubaFormIO** [comment]
> This will have other undesired consequences. `checkData` also performs calculations on change as well as performs conditional logic. This will basically make it so that if a component has "onBlur" validation, it's calculations and conditionals will fail to evaluate. This needs more work

But conditional logic also checks is this method was called by form submission and only in this case it may skip checking. If it was called by onblur event (without fromSubmission flag), checking will be in normal way.

**Comment by travist** [comment]
My point is that by skipping the ```checkData``` method if a component has "onBlur" and also if it is from the submission, will skip over EVERYTHING including calculations, conditionals, validations, etc... which does not fit the description of what you are trying to fix where "OnBlur validation is not working for email input". This change will affect all components and is pretty intrusive. Please find another way to solve the problem.

**Comment by AlehKatsiubaFormIO** [comment]
> My point is that by skipping the `checkData` method if a component has "onBlur" and also if it is from the submission, will skip over EVERYTHING including calculations, conditionals, validations, etc... which does not fit the description of what you are trying to fix where "OnBlur validation is not working for email input". This change will affect all components and is pretty intrusive. Please find another way to solve the problem.

Yeah, I understood.

**Pull request merged**
