### PR TITLE
PDF 48 - Added 'Fixed size' checkbox for textarea edit form

### PR DESCRIPTION
**Pull request by dianatsevan**

### CODE REVIEW

**Comment by travist** [comment]
Where is this being used?  Why is it needed?

**Comment by dianatsevan** [comment]
> Where is this being used? Why is it needed?
Owing to this checkbox user have an ability to fix the set sizes of the textarea so that in view mode the component won't be expanded regarding how many text is in it. The customer wanted to have it adjustable.

**Comment by travist** [comment]
Right, but what I see so far is just the ability to set the configuration. Where in the renderer does it actually do something?

**Comment by dianatsevan** [comment]
Another PR was added to formio-pdf

**Comment by travist** [comment]
So if this only applies to PDF forms, then can we only show this checkbox if the display of the form is "pdf"?

**Comment by dianatsevan** [comment]
Discussed it with Yury and we decided to make it common because we can switch between pdf view and web form view and user should see all the options.

**Comment by travist** [comment]
I think what we should do here is add this to the "Overlay Settings" which are already only applicable to PDF forms.

**Comment by dianatsevan** [comment]
Okay, will do that and ping you.

**Comment by dianatsevan** [comment]
Updated.

**Pull request merged**
