### PR TITLE
FIO-1317: Implements capability to use NextGen Rules Engine from premium in 4x.

### PR DESCRIPTION
**Pull request by MaksimFalei**

### CODE REVIEW

**Comment by travist** [comment]
I would prefer to use the "hook" system instead of having special chunks of code included (using the isNextGen). Then the rules plugin can just implement the "hooks" to inject its logic where needed.

**Comment by MaksimFalei** [comment]
> I would prefer to use the "hook" system instead of having special chunks of code included (using the isNextGen). Then the rules plugin can just implement the "hooks" to inject its logic where needed.

Fixed as mentioned.

**Comment by travist** [comment]
Needs to be rebased.

**Comment by MaksimFalei** [comment]
Solved conflicts

**Pull request merged**
