### PR TITLE
Support custom column width, offset, push and pull

### PR DESCRIPTION
**Pull request by douglaselee**
Like ngFormio does.

### CODE REVIEW

**Comment by travist** [comment]
We can probably get rid of this code now as well. This was attempting to calculate the width based on how many columns. It can go away.

https://github.com/formio/formio.js/blob/master/src/components/columns/Columns.js#L11

**Comment by douglaselee** [comment]
Yes, I saw that but left it in for backward compatibility with forms created before they could be customized.  If you're sure then I can take it out.

**Comment by travist** [comment]
It is an undocumented and hidden feature. It can be removed.

**Comment by douglaselee** [comment]
OK, will do.  What do you recommend for the default width if none is specified for a given column?  I used 0 for the default offset, push and pull.

Speaking of undocumented and hidden features can I ask what is the purpose of the commits to ngFormio and ngFormBuilder like 'Updated renderer to support iframes.' related to iframes and PDFs?  Looks like it could evolve into something very useful.  Sorry, I know this is not the right place to ask but I'm not sure what the right place would be.

**Comment by douglaselee** [comment]
Also, in what sense is the column customization hidden?  I see it at https://portal.form.io.

**Comment by travist** [comment]
@douglaselee send me an email @ travis at form.io. I will setup a GotoMeeting with you and fill you in on all the PDF form stuff we are working on. It would also be great to personally connect with you to thank you for all the amazing work you have been doing in our open source repos.

**Comment by douglaselee** [comment]
@travist thanks, will email you in a moment and include my cell phone number.  If it's easier you can just give me a call.  I don't have GotoMeeting installed yet and am not much to look at anyway.  Either way will be great to connect.

**Comment by travist** [comment]
Looks good. Thanks!

**Comment by douglaselee** [comment]
Happy to help!

**Pull request merged**
