### PR TITLE
Improve datetime expected flatpickr locale: Convert possible IETF language tag to 2 chars.

### PR DESCRIPTION
**Pull request by bobslee**
Examples (from IETF to expected flatpicker locale):
- en-US: en
- en-GB: en
- zh-CN: zh
- zh-HK: zh

### CODE REVIEW

**Comment by bobslee** [comment]
This still needs to be improved.

First check whether the locale exists in `flatpickr.l10ns`.
If not exist, then apply yhe `substr()`.

**Review by travist — CHANGES_REQUESTED** [review]
Thanks @bobslee I agree, there still needs to be some work with this. I will set it as "Request Changes" until you make those improvements.

**Comment by bobslee** [comment]
@travist Is the `flatpickr` module/object present in global scope or in the component?

**Comment by travist** [comment]
We use ```Formio.requireLibrary``` to bring in the Flatpickr dependency. This is a lazy-loading method which will first check for the global flatpickr and if not found dynamically load it and inject it into the CalendarWidget.

**Comment by bobslee** [comment]
I shall proceed this in a different (specific) branch.

**Pull request closed without merging**
