### PR TITLE
FJS-1239: Adds ability to create shortcut buttons for flatpickr

### PR DESCRIPTION
**Pull request by alexandraRamanenka**
FJS-1239

### CODE REVIEW

**Comment by travist** [comment]
Needs to be rebased.

**Review by travist — CHANGES_REQUESTED** [review]
Needs to be rebased.

**Comment by alexandraRamanenka** [comment]
> Needs to be rebased.

Done

**Comment by travist** [comment]
Needs to be rebased again. sorry.

**Pull request merged**
