### PR TITLE
FIO-4833: Removes Hide Label setting from Well, Columns, Tabs and Table components since they do not render a label

### PR DESCRIPTION
**Pull request by alexandraRamanenka**
https://formio.atlassian.net/browse/FIO-4833

Just removed Hide Label setting from the components that don't have a label at all
No tests needed since it just hides a redundant setting

### CODE REVIEW

**Review by TanyaGashtold — CHANGES_REQUESTED** [review]
Please confirm that all tests are passing locally

**Review by TanyaGashtold — APPROVED** [review]

**Comment by brendanbond** [comment]
@alexandraRamanenka @TanyaGashtold how are we running these tests? This branch the tests fail locally for me and I have far more (> 2,016 tests rather than 1,492)

**Review by brendanbond — CHANGES_REQUESTED** [review]
I can confirm that tests are failing locally, make sure we run `yarn test` rather than `yarn test:unit` so it rebuilds the lib folder.

Screen Shot 2023-05-16 at 9 34 32 AM

**Comment by alexandraRamanenka** [comment]
> I can confirm that tests are failing locally, make sure we run `yarn test` rather than `yarn test:unit` so it rebuilds the lib folder.
> 
> Screen Shot 2023-05-16 at 9 34 32 AM

This test is passing for me, hovewer, some of those webform tests do not work consistently. 
Also, if you check CirscleCI, you'll see that there are 1480 test cases on the master branch. It may differ for you because the 'test' script runs 'templates' script and 'test:unit' scipt. Also I run 'gulp bild && npm run transpile' before the tests script each time
image

**Comment by TanyaGashtold** [comment]
@alexandraRamanenka, all tests are fixed on the master branch. Can you please just rebase this branch against master, in this case CircleCi will run the updated tests. If they are passing, all questions will be answered.

**Comment by travist** [comment]
👍

**Pull request merged**
