### PR TITLE
FIO-2668: fixed an issue where translation does not work for any language if en translation is provided for this value…

### PR DESCRIPTION
**Pull request by TanyaGashtold**

### CODE REVIEW

**Comment by elibus** [comment]
@llaurentiu this should be linked to #3935

**Comment by llaurentiu** [comment]
@elibus they are related but not the same issue. I disabled #3935 and created https://github.com/formio/formio.js/pull/3954 that is linked to a defect I created (https://github.com/formio/formio.js/issues/3955)

**Comment by elibus** [comment]
@llaurentiu yep, you are right, it should be #3911 instead. Correct?

**Comment by llaurentiu** [comment]
@elibus yes. didn't check that they created another defect for the same issue. I closed mine.

**Pull request merged**
