### PR TITLE
Pull request to fix an issue with File component

### PR DESCRIPTION
**Pull request by asalhani**
I'm submtting this pull request as a suggested fix for an issue I discoved in File component. The issue was when you select **base64** as a storage in builder mode, in the submission, I couldn't upload the file and I kept getting error message:

> File Service not provided.

[File.zip](https://github.com/formio/formio.js/files/1923567/File.zip)

To fix this issue, I came an [opened  defect](https://github.com/formio/formio.js/issues/337), and I applied the suggested fix by @travist and @StephenOTT and it worked. The only remaining issue, which wait @travist fix as he promised is to fix base64 data duplicate in url and data fields which severally affect form rendering time especially if you have multiple files.

Suggested fixed code:
`

>   get fileService() {
>     if (this.options.fileService) {
>       return this.options.fileService;
>     }
>     if (this.options.formio) {
>       return this.options.formio;
>     }
>     return new Formio();
>   }

`

Now, in the submission mode for File component, the current implementation for _getFile()_ method is not valid anymore since Chrome has disabled the ability to open base64 images. So I modified the implementation to open file in a workaround using the _download_ property in HTML 5.

```
  getFile(fileInfo, event) {
    const fileService = this.fileService;
    if (!fileService) {
      return alert('File Service not provided');
    }
    fileService.downloadFile(fileInfo).then((file) => {
      if (file) {
        // commented becouse this way is not supported any more by chrome due to security practices.
        //window.open(file.url, '_blank');

        // this is a workaround to render base64 files in Chrome. Still not working on IE/Edge
        var hiddenElement = document.createElement('a');
        hiddenElement.href = 'data:' + file.type + ';base64,' + encodeURI(file.data);
        hiddenElement.target = '_blank';
        hiddenElement.download = file.originalName;
        hiddenElement.click();
      }
    })
      .catch((response) => {
        // Is alert the best way to do this?
        // User is expecting an immediate notification due to attempting to download a file.
        alert(response);
      });
    event.preventDefault();
  }
```

Please let me know if you need any further clarification.

### CODE REVIEW

**Comment by StephenOTT** [comment]
@travist  thoughts on this fix?

**Comment by travist** [comment]
I agree with these changes, but the one that concerns me is the change in how files are downloaded. I am worried because it removes the attempt at ```window.open```. Can we implement this as a fallback? Something like this?

```js
try {
  window.open(file.url, '_blank');
}
catch (err) {
  var hiddenElement = document.createElement('a');
  hiddenElement.href = 'data:' + file.type + ';base64,' + encodeURI(file.data);
  hiddenElement.target = '_blank';
  hiddenElement.download = file.originalName;
  hiddenElement.click();
}
```

This would work in Chrome if it throws an exception on ```window.open``` which I assume it does now due to the security changes.

**Comment by asalhani** [comment]
@travist so should i open a new pull request with your suggested code or you can handle it within this one?

**Comment by travist** [comment]
I would like if you would test the above change and if it works for you update this pull request with that change.

**Comment by asalhani** [comment]
@travist sure no problem. I know it's out of this topic, but I really appreciate your kind input on a question I raised before. Thanks in advance.

https://github.com/formio/angular-formio/issues/166

**Comment by randallknutson** [comment]
Hi asalhani, thanks for the commit. Could you clean up the diff for this pull request so it only shows the changes you actually made? Currently it shows a lot of stuff including the dist folder changes which makes it impossible to see what is being done. Thanks!

**Pull request closed without merging**
