### PR TITLE
NUMBER - Bug Fix: couldn't set empty value

### PR DESCRIPTION
**Pull request by Aiso786**
If i clear a Number field's value, the new value isn't sent to the server.
This pull request resolves this issue.

### CODE REVIEW

**Comment by travist** [comment]
This was fixed before...
 - https://github.com/formio/formio.js/commit/9af675b1f1b59f7e71afda26b7847913523f95f0

Is there a way for you to better describe why returning "undefined" is a problem?

**Comment by Aiso786** [comment]
When we return "undefined", the related property is missing in the "submission" object . I think the property should still figure in the object with a null or undefined value.

However, if you guys don't think like that, it's better to reject this pull request.

And i think returning `''` is not a good idea.

**Comment by travist** [comment]
Yeah, that is what I am thinking as well. A number should never return an empty string. I am fine with either ```null``` or ```undefined``` so I am thinking that this issue that you are talking about may be caused elsewhere.

**Comment by Aiso786** [comment]
Alright, i close this PR and will look for another way to fix the issue.
Thanks @travist

**Pull request closed without merging**
