### PR TITLE
noNewModal = true to skip new component modal

### PR DESCRIPTION
**Pull request by besmiralia**
Add this flag to the predefined components to skip the modal popup.
Referring to the example:
https://formio.github.io/formio.js/app/examples/custombuilder.html

components: {
        firstName: {
          title: 'First Name',
          key: 'firstName',
          icon: 'terminal',
          schema: {
            label: 'First Name',
            type: 'textfield',
            key: 'firstName',
            input: true,
            **noNewModal: true**
          }
        },...

The components under the custom group can have the property noNewModal = true if you want to skip the modal.
Any other component that doesn't have the flag (ex. basic, data, etc) keep their regular behavior (modal popup when dragged/dropped on the form)

### CODE REVIEW

**Comment by travist** [comment]
We already have a flag for this called ```noNewEdit```.  You can add it to the builder like so.

```js
Formio.builder(document.getElementById('builder'), {}, {
  noNewEdit: true
});
```

**Comment by besmiralia** [comment]
Hi @travist.
Yes, I noticed that flag, but once you initialize the builder with it, it applies to every component. What I created is a flag for a specific component.

Let's say, I created a custom group and there I have already predefined resource components(ex. FirstName, LastName, etc, just like the example). Now I don't want to waste time clicking save every time I drop them into the form, they are already predefined, there is nothing else to customize. But I want to leave the popup for new elements that I create, ex. new fields or maybe all layout components. Makes sense?

**Comment by travist** [comment]
I am alright with this as long as we give it the same name ```noNewEdit```.  I would prefer to have a consistent name for a variable that does the same thing as the global option.

**Comment by besmiralia** [comment]
Agreed, I'll make the change and resubmit

**Pull request merged**
