### PR TITLE
Add submission as form creation option

### PR DESCRIPTION
**Pull request by paulfalgout**
I couldn't actually get the test to run.  Too many failing tests, but this works in a jsfiddle for at least the use cases I'm aware of.

Solves: https://github.com/formio/formio.js/issues/3687
~~Fixes: https://github.com/formio/formio.js/issues/3684~~. It addresses this issue, but this issue is still broken if you're using the submission in the regular fashion of setting it in the `then`

### CODE REVIEW

**Comment by paulfalgout** [comment]
Screen Shot 2022-02-13 at 11 52 35 PM
FWIW on a datagrid if this is set to true it'll clear out the related data on a submission set at instantiation

**Comment by travist** [comment]
I like it!!! We are working on the failing tests but I see no reason to include this in the 4.15.x version

**Comment by paulfalgout** [comment]
@travist been using this for a couple of weeks now by just overriding the prototype and honestly it's cleared up a lot of quirks we were working around.

**Comment by TriStarGod** [comment]
Hi @paulfalgout , could you give me an example of how you are overriding the prototype to get this functionality? There are couple of features I want to use but currently waiting on merges.

**Comment by travist** [comment]
This will be part of the 5.x release!  Thank you for your contribution!

**Pull request merged**
