### PR TITLE
Add Gmap Component

### PR DESCRIPTION
**Pull request by neolanders**
Adding new component to display googleMap:

Behaviors:
- User enter an address (google.maps.places.Autocomplete) and select it from autocomplete
- A Marker is display on the Map
- User can move (drag) the marker and the address is set in the input field.

This component was done to answer our requirement,
Please let me know if there is anything else need to be done in this component in order to push it.
Thanks

**Screenshot**

gmap

**Sample Use:**

```
{
  "input": true,
  "tableView": true,
  "label": "gmap",
  "key": "gmap",
  "placeholder": "",
  "multiple": false,
  "protected": false,
  "clearOnHide": true,
  "unique": false,
  "persistent": true,
  "map": {
    "gmapId": "googleMap",
    "region": ".ca",
    "key": "YOUR_GOOGLE_KEY_HERE",
    "autocompleteOptions" : {
      "componentRestrictions" : {
        "country" : [
          "ca"
        ]
      }
    }
  },
  "validate": {
    "required": false
  },
  "type": "gmap",
  "tags": [

  ],
  "conditional": {
    "show": "",
    "when": null,
    "eq": ""
  }
}

```

### CODE REVIEW

**Comment by travist** [comment]
I just merged this into the master branch. Thanks!

**Comment by neolanders** [comment]
Thank you, can please add me to the contributor list for that.

**Comment by sabnandha** [comment]
Hi, I'm trying to use gmap in my project ? but in  the  latest version of the formio js version(formio.js-4.13.0-rc.13) Gmap component is not available. can any one help me with this issue

**Comment by wag110894** [comment]
@sabnandha, 

This feature has since been deprecated.

**Pull request closed without merging**
