### PR TITLE
S3 photo upload - update File.js

### PR DESCRIPTION
**Pull request by oneserve-alh**
Fix for uploading photos to S3 from mobile devices.

### CODE REVIEW

**Comment by oneserve-alh** [comment]
Resolves #2865

**Comment by travist** [comment]
Looks good, thanks!

**Comment by travist** [comment]
I just realized that this forces all files to be named "photo-......png".  We will need to revert this until we figure out a way to make it work for all file types.

**Comment by travist** [comment]
You will need to create a new Pull Request with this + fixes.

**Comment by oneserve** [comment]
Created PR #2874 which includes this plus:

- Set blob.name to file.name so that the original naming convention is used.
- Removed unused "evt" param'.
- Removed unnecessary console.log().

**Pull request merged**
