### PR TITLE
Add limitations for file component

### PR DESCRIPTION
**Pull request by douglaselee**
Borrowed code from ng-file-upload.
See related PRs in ngFormio and ngFormBuilder.

### CODE REVIEW

**Comment by travist** [comment]
Awesome @douglaselee! Thanks for taking the time to do this. We will pull this into the next major release.

**Comment by douglaselee** [comment]
Happy to help @travist.  Thanks for upcoming merge!

**Comment by travist** [comment]
Thanks again @douglaselee! Just now getting through these pull requests.

**Comment by douglaselee** [comment]
Happy to help @travist!

**Pull request merged**
