### PR TITLE
FIO-8645: day component required validation error not correct

### PR DESCRIPTION
**Pull request by ZenMasterJacob20011**
## Link to Jira Ticket

https://formio.atlassian.net/browse/FIO-8645

## Description

**What changed?**

Previously, formio.js did not have the requiredDayField translation key in the en.js file which caused the required validation to not display correctly. This PR replaces this behavior by adding requiredDayField translation key to the translation file

## Dependencies

N/A

## How has this PR been tested?

I added automated tests and manually tested

## Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if applicable)
- [x] My changes generate no new warnings
- [x] My changes include tests that prove my fix is effective (or that my feature works as intended)
- [x] New and existing unit/integration tests pass locally with my changes
- [x] Any dependent changes have corresponding PRs that are listed above

### CODE REVIEW

**Review by travist — CHANGES_REQUESTED** [review]
Couldn't we also fix this by just changing "requiredDayField" to just "required" and not introduce a new translation that is exactly the same as "required"?

**Review by ZenMasterJacob20011 — COMMENTED** [review]
In @formio/core/src/process/validation/rules there is a file called validateRequiredDay.ts. This seems to be added in because you can set the required validation check on the day, month, and year inputs individually. Right now we have three translation keys for the day component and that is requiredDayField, requiredMonthField, and requiredYearField. I can either ...
- change requiredDayField, requiredMonthField, and requiredYearField to just required
- delete the validateRequiredDay.ts file and pass the responsibility back to some function inside the validateRequired.ts file. This would require a check to see if the component is a day component and some extra validation checking due to the fact that you can set required validations for day, month, and year individually.

I've also just noticed that even if you have required validation on for all of them, the validator will only throw an error for one of them in the order of day, month, and year. So if you have all of them set to required only the day will be marked as a required error

**Review by brendanbond — CHANGES_REQUESTED** [review]
left a comment

**Comment by ZenMasterJacob20011** [comment]
Added core tests and translations
https://github.com/formio/core/pull/119

**Review by ZenMasterJacob20011 — COMMENTED** [review]
reviewed

**Review by brendanbond — APPROVED** [review]

**Pull request merged**
