### PR TITLE
Add StripeCheckout component

### PR DESCRIPTION
**Pull request by GuillaumeSmaha**
Hi,

This a new component to integrate a payment button using Stripe.
For context, Stripe will get the card and payment information and will return a token which will use on backend to made the payment.
So, the component is based on ButtonComponent and on click event, it will show the Stripe popup. After validation of information, Stripe send a request on their server and in response, the obtained token will be saved in the form data.

The component also manage the case where the button can submit the form after saving the token in the data. (action="submit" for this case)

### CODE REVIEW

**Comment by travist** [comment]
This is awesome! I am wondering if we should start a ```contrib``` folder for all of the contributed components and this would be a good candidate for that. Others that I can think of are things like ReCaptcha, etc. You could then include it using the following.

```js
import { Formio } from 'formiojs/full';
import { StripeCheckoutComponent } from 'formiojs/contrib/stripe/StripeCheckout';
Formio.registerComponent('stripeCheckout', StripeCheckoutComponent);
```

Let me know what you think. This would probably need to go into a ```src/contrib``` folder, and then we would have a build routine run that through Babel to create the root ```contrib``` folder.

**Comment by GuillaumeSmaha** [comment]
Yes, good idea. It will avoid to overload the component directory with basic component.
Gmap component could also be moved to this directory (or not for compatibility)

**Comment by GuillaumeSmaha** [comment]
@travist I moved the component in `contrib` directory

**Comment by travist** [comment]
Thank you for making this change. I am happy to include it now that it is in contrib folder.

**Pull request merged**
