### PR TITLE
FJS-1144 Dynamic Select Filtering - Refresh On does not work

### PR DESCRIPTION
**Pull request by kzhang-dsg**

### CODE REVIEW

**Comment by travist** [comment]
This makes sense to me, but I do believe that this may cause regressions in other places of the renderer. I also believe that this is the same thing as just removing the ```changePath``` variable and check all together. I would prefer to save this for the ```4.13.x``` release since it may require more extensive testing.

**Comment by kzhang-dsg** [comment]
Hi @travist, I agree. I kept the `changePath` variable for regression so that if there are any place that depends on the `changePath` will still work (but it should not be any).

**Comment by travist** [comment]
The issue I see happening is if you have two components in a form with the same key (like one in a DataGrid and the other at the root), this will trigger erroneous refreshes on the other fields. This may require some more thought. What is the bug you are trying to fix here? Maybe we can fix this another way?

**Comment by kzhang-dsg** [comment]
Hi @travist, the issue I was trying to fix is: FJS-1144 a.k.a. https://github.com/formio/formio.js/issues/3108

**Comment by travist** [comment]
I believe we fixed this in master branch. Please confirm.

**Pull request closed without merging**
