### PR TITLE
FJS-1103: When you hit the enter button, then you see the field not saving the year correctly.

### PR DESCRIPTION
**Pull request by AlehKatsiubaFormIO**

### CODE REVIEW

**Comment by travist** [comment]
Needs tests.

**Comment by elibus** [comment]
Please check #3277 
I think blocking the event propagation on enter won't fix the case when the blur event is triggered after clicking on another component.

**Comment by travist** [comment]
I agree with @elibus. We also need to handle this case as well. @AlehKatsiubaFormIO please handle this case as well.

**Comment by AlehKatsiubaFormIO** [comment]
@travist @elibus 
Case when the blur event is triggered after clicking on another component already have been fixed [here](https://github.com/formio/formio.js/pull/3227/files).

**Comment by elibus** [comment]
@AlehKatsiubaFormIO #3227 introduced a new bug reported in #3277 which is unfortunately closed but the bug is still there. 
There is a codepen in the ticket, if you open it you will see that when a date is picked and you next click on any other component, the date picked is has year 3 years ahead.

**Review by travist — CHANGES_REQUESTED** [review]
Need to better handle blur event handling.

**Pull request merged**
