### PR TITLE
roll back flatpickr version to 4.6.2

### PR DESCRIPTION
**Pull request by RomanLetsuk**

### CODE REVIEW

**Comment by travist** [comment]
Why?  We need a commit message or something explaining why we need to do this so that when I go an upgrade again I can be aware of why we downgraded.

**Comment by RomanLetsuk** [comment]
@travist we need to roll back because version 6.4.3 has an issue that doesn't allow to clear input for the DateTime component.

**Comment by travist** [comment]
You need to actually "pin" the version then...  ```^4.6.2``` will still pull in 4.6.3.

**Comment by travist** [comment]
I'll pin it.

**Pull request merged**
