### PR TITLE
Bugfix/fix adress region

### PR DESCRIPTION
**Pull request by neolanders**
I found this bug  on adress Component, the region parametter was not use.

### CODE REVIEW

**Comment by travist** [comment]
Please make this pull request reference the 2.x branch.

**Comment by neolanders** [comment]
I'm working with @GuillaumeSmaha, he already move this fix into the branch  (2.x)

**Comment by randallknutson** [comment]
2.x has been merged into master

**Comment by travist** [comment]
This is now part of master.

**Pull request closed without merging**
